import tkinter as tk

window = tk.Tk()
window.title('Calculator')
window.geometry('350x350')
window.resizable(False, False)
button_add = tk.Button(window, text='+',width=2, height=2)
button_add.place(x = 100, y = 200)
button_sub = tk.Button(window, text='-',width=2, height=2)
button_sub.place(x = 150, y = 200)
button_mul = tk.Button(window, text='*',width=2, height=2)
button_mul.place(x = 200, y = 200)
button_div = tk.Button(window, text='/',width=2, height=2)
button_div.place(x = 250, y = 200)
number1_entery = tk.Entry(window, width = 28)
number1_entery.place(x = 100, y = 75)
number2_entery = tk.Entry(window, width = 28)
number2_entery.place(x = 100, y = 150)
answer_entery = tk.Entry(window, width = 28)
answer_entery.place(x = 100, y = 290)
number1 = tk.Label(window, text = 'Enter number one: ')
number1.place(x = 100, y = 50)
number2 = tk.Label(window, text = 'Enter number two: ')
number2.place(x = 100, y = 125)
answer = tk.Label(window, text = 'Result: ')
answer.place(x = 100, y = 260)
window.mainloop()